# Generated by Django 5.1.4 on 2025-01-12 10:09

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=200, verbose_name='업체명')),
                ('placeNum', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='업체 전화 번호')),
                ('address', models.TextField(verbose_name='주소')),
                ('area', models.CharField(max_length=100, verbose_name='지역')),
                ('placeImage', models.ImageField(upload_to='photos/', verbose_name='업체 사진')),
                ('partNum', models.IntegerField(default=0, verbose_name='참가자 수')),
                ('duplPartNum', models.IntegerField(default=0, verbose_name='중복 참가자 수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='최종 수정일')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.boardmember', verbose_name='작성자')),
            ],
            options={
                'verbose_name': '업체 게시판',
                'verbose_name_plural': '업체 게시판',
                'db_table': 'placeBoards',
            },
        ),
    ]
