# Generated by Django 5.1.4 on 2025-01-14 13:22

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeBoard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeboard',
            name='address',
            field=models.TextField(max_length=100, verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='placeboard',
            name='area',
            field=models.CharField(max_length=50, verbose_name='지역'),
        ),
        migrations.AlterField(
            model_name='placeboard',
            name='place',
            field=models.CharField(max_length=50, verbose_name='업체명'),
        ),
        migrations.AlterField(
            model_name='placeboard',
            name='placeNum',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=15, region=None, verbose_name='업체 전화 번호'),
        ),
    ]
