# Generated by Django 5.1.4 on 2025-02-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeBoard', '0003_alter_placeboard_placenum'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeboard',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='위도'),
        ),
        migrations.AddField(
            model_name='placeboard',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='경도'),
        ),
    ]
