# Generated by Django 5.1.4 on 2025-01-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_content_post_contents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='기본키')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('num', models.CharField(max_length=20, verbose_name='전화번호')),
                ('mail', models.EmailField(max_length=254, verbose_name='이메일')),
                ('placeId', models.IntegerField(verbose_name='업체 기본키')),
                ('dupl', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '이벤트 참여자',
                'verbose_name_plural': '이벤트 참여자',
                'db_table': 'event_participants',
            },
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
