# Generated by Django 5.1.4 on 2025-01-29 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_participant_remove_answer_question_delete_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='mail',
        ),
    ]
